/* BIA Product Studio runtime — Apache-2.0; see LICENSE and NOTICE. */
'use strict';
const BiaCore=(()=>{
 const limit=500;
 function text(s,n,empty=false){if(typeof s!=='string'||s.length>n||(!empty&&!s.trim())||/[\u0000-\u001f\u007f]/.test(s))throw Error('Nội dung không hợp lệ');return s.trim();}
 function integer(v,max=1000000){if(!/^\d+$/.test(String(v)))throw Error('Cần số nguyên không âm');const n=Number(v);if(!Number.isSafeInteger(n)||n>max)throw Error('Số vượt giới hạn');return n;}
 function minor(v,currency){const d=currency==='VND'?0:2;const re=d?/^\d{1,13}(?:\.\d{1,2})?$/:/^\d{1,13}$/;if(!re.test(String(v)))throw Error('Đơn giá không hợp lệ; dùng dấu chấm thập phân');const [a,b='']=String(v).split('.');const n=BigInt(a)*10n**BigInt(d)+BigInt(b.padEnd(d,'0')||'0');if(n>1000000000000n*10n**BigInt(d))throw Error('Đơn giá quá lớn');return n.toString();}
 function decimal(v,currency){const d=currency==='VND'?0:2;let s=BigInt(v).toString().padStart(d+1,'0');return d?s.slice(0,-d)+'.'+s.slice(-d):s;}
 function money(v,currency){const [a,b]=decimal(v,currency).split('.');return a.replace(/\B(?=(\d{3})+(?!\d))/g,',')+(b===undefined?'':'.'+b)+' '+currency;}
 function date(s){if(s==='')return s;if(!/^\d{4}-\d\d-\d\d$/.test(s))throw Error('Ngày không hợp lệ');const d=new Date(s+'T00:00:00Z');if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==s)throw Error('Ngày không tồn tại');return s;}
 function fields(defs=[]){if(!Array.isArray(defs)||defs.length>12)throw Error('Cấu trúc trường không hợp lệ');const ids=new Set();return defs.map(f=>{if(!f||!/^f-[a-zA-Z0-9-]{1,62}$/.test(f.id)||ids.has(f.id)||!['text','number','date','choice'].includes(f.kind)||typeof f.required!=='boolean'||!Array.isArray(f.options))throw Error('Trường không hợp lệ');ids.add(f.id);const label=text(f.label,60);const options=f.options.map(v=>text(v,60));if(new Set(options).size!==options.length||(f.kind==='choice'?(options.length<1||options.length>12):options.length!==0))throw Error('Lựa chọn không hợp lệ');return {id:f.id,label,kind:f.kind,required:f.required,options};});}
 function compatible(oldDefs,newDefs){const old=fields(oldDefs),next=fields(newDefs);for(const f of old){const n=next.find(x=>x.id===f.id);if(!n||n.kind!==f.kind||(!f.required&&n.required)||f.options.some(v=>!n.options.includes(v)))throw Error('Cấu trúc không tương thích; giữ bản sao lưu và dùng phiên bản cũ');}for(const n of next)if(n.required&&!old.some(f=>f.id===n.id))throw Error('Không tự thêm trường bắt buộc vào dữ liệu cũ');return true;}
 function extra(raw,defs){raw=raw===undefined?{}:raw;if(!raw||typeof raw!=='object'||Array.isArray(raw)||Object.keys(raw).some(k=>!defs.some(f=>f.id===k)))throw Error('Có trường lạ; không tự bỏ dữ liệu');const out={};for(const f of defs){let v=raw[f.id]===undefined?'':raw[f.id];if(typeof v!=='string')throw Error(f.label+': cần dữ liệu văn bản');v=v.trim();if(!v){if(f.required)throw Error(f.label+': bắt buộc');out[f.id]='';continue;}if(f.kind==='number'&&!/^-?\d{1,12}(?:\.\d{1,4})?$/.test(v))throw Error(f.label+': số không hợp lệ');if(f.kind==='date')date(v);if(f.kind==='choice'&&!f.options.includes(v))throw Error(f.label+': chọn một giá trị hợp lệ');out[f.id]=text(v,240);}return out;}
 function row(r,kind,currency,defs=[]){
  if(!r||typeof r!=='object'||Array.isArray(r))throw Error('Dòng dữ liệu không hợp lệ');
  const x={id:text(r.id,80),name:text(r.name,120),note:text(r.note,500,true)};
  if(!/^[a-zA-Z0-9-]+$/.test(x.id))throw Error('ID không hợp lệ');
  if(kind==='tasks'){x.due=date(r.due);x.priority=integer(r.priority,3);if(x.priority<1||!['todo','doing','done'].includes(r.status))throw Error('Trạng thái/ưu tiên sai');x.status=r.status;}
  else {x.qty=integer(r.qty);if(kind==='stock'){x.sku=text(r.sku,60);x.threshold=integer(r.threshold);}else if(kind==='quote'){if(typeof r.price!=='string'||!/^\d{1,15}$/.test(r.price))throw Error('Đơn giá sai');x.price=minor(decimal(r.price,currency),currency);}else throw Error('Loại sản phẩm sai');}
  const extras=extra(r.extra,fields(defs));if(defs.length)x.extra=extras;return x;
 }
 function validate(rows,kind,currency,defs=[]){if(!Array.isArray(rows)||rows.length>limit)throw Error('Tối đa 500 dòng');const out=rows.map(r=>row(r,kind,currency,defs));const ids=new Set(),skus=new Set();for(const r of out){if(ids.has(r.id))throw Error('Trùng ID');ids.add(r.id);if(kind==='stock'){const key=r.sku.toLocaleLowerCase();if(skus.has(key))throw Error('Trùng mã hàng');skus.add(key);}}return out;}
 function total(rows){return rows.reduce((s,r)=>s+BigInt(r.price)*BigInt(r.qty),0n).toString();}
 function cell(s){s=String(s);if(/^[\s]*[=+\-@]/.test(s)||/^[\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
 function csv(rows,kind,currency,defs=[]){defs=fields(defs);const columns=kind==='tasks'?['name','due','priority','status','note']:kind==='stock'?['sku','name','qty','threshold','note']:['name','qty','price','note'];return '\ufeff'+[[...columns,...defs.map(f=>f.label)],...rows.map(r=>[...columns.map(k=>k==='price'?decimal(r[k],currency):r[k]),...defs.map(f=>r.extra?.[f.id]||'')])].map(a=>a.map(cell).join(',')).join('\r\n');}
 function backup(rows,p){const out=JSON.stringify({schema:'BIA_PRODUCT_DATA_2',id:p.id,kind:p.kind,currency:p.currency,fields:fields(p.fields||[]),rows:validate(rows,p.kind,p.currency,p.fields||[])},null,2);if(new TextEncoder().encode(out).length>1000000)throw Error('Dữ liệu vượt 1 MB; giảm số dòng hoặc độ dài trước khi lưu');return out;}
 function restore(raw,p){if(typeof raw!=='string'||raw.length>1000000)throw Error('Tệp quá lớn');const x=JSON.parse(raw);if(!['BIA_PRODUCT_DATA_1','BIA_PRODUCT_DATA_2'].includes(x.schema)||x.id!==p.id||x.kind!==p.kind||x.currency!==p.currency)throw Error('Bản sao lưu không khớp sản phẩm/tiền tệ');if(x.schema==='BIA_PRODUCT_DATA_2'&&!Array.isArray(x.fields))throw Error('Thiếu cấu trúc dữ liệu');compatible(x.schema==='BIA_PRODUCT_DATA_1'?[]:x.fields,p.fields||[]);return validate(x.rows,p.kind,p.currency,p.fields||[]);}
 function selftest(){let count=0;const check=(x)=>{if(!x)throw Error('Kiểm tra thất bại');count++;};check(minor('1.25','USD')==='125');check(total([{price:'99999999999999',qty:1000000}])==='99999999999999000000');check(csv([{name:'=1+1',qty:1,price:'100',note:''}],'quote','VND').includes("'=1+1"));try{date('2026-02-30');throw Error('accepted');}catch(e){check(e.message!=='accepted');}return count;}
 return Object.freeze({fields,compatible,integer,minor,decimal,money,row,validate,total,csv,backup,restore,selftest});
})();
if(typeof module!=='undefined')module.exports=BiaCore;
