use bia_core::product_studio::{compile,compile_wire,Spec};
fn spec()->Spec{Spec{id:"product-0001".into(),kind:"quote".into(),title:"Báo giá Việt".into(),audience:"Nhóm dịch vụ".into(),brief:"Tạo bảng báo giá trước thuế".into(),author:"Người tạo".into(),currency:"VND".into(),accent:"#176b5b".into(),fields:vec![]}}
#[test] fn round_trip_and_deterministic_deliverables(){let s=spec();let restored=Spec::parse(&s.wire()).unwrap();assert_eq!(compile(&s).unwrap(),compile(&restored).unwrap());let files=compile(&s).unwrap();assert_eq!(files.len(),11);assert!(files.iter().all(|(p,_)|!p.contains('/')&&!p.contains("..")));assert!(files.iter().any(|(p,t)|p=="LICENSE"&&t.contains("Apache License")));}
#[test] fn untrusted_brief_stays_data(){let mut s=spec();s.brief="</script><script>alert(1)</script>\\\"".into();let files=compile(&s).unwrap();let config=&files.iter().find(|(p,_)|p=="config.js").unwrap().1;assert!(!config.contains("</script>"));assert!(config.contains("\\u003c"));assert!(!files.iter().find(|(p,_)|p=="index.html").unwrap().1.contains("alert(1)"));}
#[test] fn rejects_unsupported_and_oversized_specs(){let mut s=spec();s.kind="arbitrary-saas".into();assert!(compile(&s).is_err());s=spec();s.accent="red;url(x)".into();assert!(compile(&s).is_err());s=spec();s.id="../../escape".into();assert!(compile(&s).is_err());assert!(compile_wire(&"a".repeat(16001)).starts_with("ERROR"));s=spec();s.brief="x".repeat(2001);assert!(compile(&s).is_err());}
#[test] fn all_product_kinds_are_supported(){for kind in ["quote","stock","tasks"]{let mut s=spec();s.kind=kind.into();let files=compile(&s).unwrap();assert!(files.iter().any(|(p,t)|p=="config.js"&&t.contains(kind)));assert!(files.iter().any(|(p,t)|p=="QA.json"&&t.contains("not_yet_verified")));}}
#[test] fn legacy_specs_and_custom_fields_round_trip(){use bia_core::product_studio::Field;let mut s=spec();let old=s.wire().lines().take(9).collect::<Vec<_>>().join("\n").replace("BIA_PRODUCT_2","BIA_PRODUCT_1");assert!(Spec::parse(&old).unwrap().fields.is_empty());s.kind="suite".into();s.fields.push(Field{id:"f-client".into(),label:"Khách hàng".into(),kind:"text".into(),required:true,options:vec![]});let parsed=Spec::parse(&s.wire()).unwrap();assert_eq!(s.fields,parsed.fields);assert!(compile(&parsed).unwrap().iter().any(|(p,t)|p=="config.js"&&t.contains("f-client")&&t.contains("suite")));}
#[test] fn incompatible_changes_are_rejected(){use bia_core::product_studio::{compatible,Field};let a=spec();let mut b=a.clone();b.fields.push(Field{id:"f-extra".into(),label:"Ghi chú khách".into(),kind:"text".into(),required:false,options:vec![]});assert!(compatible(&a,&b).is_ok());let mut c=b.clone();c.fields[0].label="Tên mới".into();c.kind="suite".into();assert!(compatible(&b,&c).is_ok());assert!(compatible(&b,&a).is_err());c.fields[0].kind="date".into();assert!(compatible(&b,&c).is_err());c=b.clone();c.fields[0].required=true;assert!(compatible(&a,&c).is_err());c=b.clone();c.currency="USD".into();assert!(compatible(&b,&c).is_err());}
#[test] fn invalid_field_definitions_fail_closed(){use bia_core::product_studio::Field;let mut s=spec();let f=Field{id:"f-status".into(),label:"Trạng thái".into(),kind:"choice".into(),required:false,options:vec!["Mới".into(),"Mới".into()]};s.fields.push(f);assert!(compile(&s).is_err());s.fields[0].options=vec!["Mới".into()];assert!(compile(&s).is_ok());s.fields.push(s.fields[0].clone());assert!(compile(&s).is_err());}
