package com.bia.mobile;
import android.test.InstrumentationTestCase;import android.content.*;import android.graphics.*;import java.io.*;import java.nio.*;import java.util.*;import java.util.zip.*;import org.json.*;

public final class AdvancedCreationTest extends InstrumentationTestCase {
    SceneEngine.Scene single(){return new SceneEngine.Scene(Collections.singletonList(SceneEngine.item("sphere",0xff55bdaa,0,0,0,1)),0,0,0.8,-0.5,512,true);}
    public void testSculptReplaySubdivisionAndLimits()throws Exception{
        MotionProject p=MotionProject.from(single());Sculpt.Stroke push=new Sculpt.Stroke("push",0.5,0,0.8,0.8,0.2,0,0,1,true);MotionProject changed=p.sculpt(0,push,1);CreativeEngine.Mesh before=SceneEngine.primitive(p.base.items.get(0).geometry(Collections.emptyList(),1)),after=SceneEngine.primitive(changed.base.items.get(0));assertEquals(p.base.items.get(0).triangles()*4,after.faces.size());assertEquals(before.vertices.size(),after.vertices.size());double distance=0;for(int i=0;i<after.vertices.size();i++)for(int k=0;k<3;k++){assertTrue(Double.isFinite(after.vertices.get(i)[k]));distance+=Math.abs(after.vertices.get(i)[k]-before.vertices.get(i)[k]);}assertTrue(distance>1);HashMap<String,Integer> edges=new HashMap<>();for(int[] f:after.faces)for(int j=0;j<3;j++){int a=f[j],b=f[(j+1)%3];String key=Math.min(a,b)+":"+Math.max(a,b);edges.put(key,edges.getOrDefault(key,0)+1);}for(int n:edges.values())assertEquals(2,n);
        assertEquals(changed.json(),MotionProject.parse(changed.json()).json());assertEquals(SceneEngine.primitive(changed.base.items.get(0)).obj(),SceneEngine.primitive(MotionProject.parse(changed.json()).base.items.get(0)).obj());
        MotionProject smooth=changed.sculpt(0,new Sculpt.Stroke("smooth",0.5,0,0.8,0.8,0.2,0,0,1,true),1);assertFalse(SceneEngine.primitive(smooth.base.items.get(0)).obj().equals(after.obj()));
        MotionProject grab=p.sculpt(0,new Sculpt.Stroke("grab",0,0,1,0.8,0.2,0,1,0,false),0);assertFalse(SceneEngine.primitive(grab.base.items.get(0)).obj().equals(SceneEngine.primitive(p.base.items.get(0)).obj()));
        try{changed.sculpt(0,push,3);fail("Subdivision bound");}catch(IllegalArgumentException expected){}try{new Sculpt.Stroke("push",0,0,0,Double.NaN,0.2,0,0,1,false);fail();}catch(IllegalArgumentException expected){}
        double[] hit=ScenePicking.pick(single(),single(),0,0.5,0.5);assertNotNull(hit);assertTrue(hit[2]>0.9);assertNull(ScenePicking.pick(single(),single(),0,0,0));
    }
    public void testKeyframeInterpolationFixedFramingAndRoundTrip()throws Exception{
        MotionProject p=MotionProject.from(single()).key(0,new MotionProject.Key(0,0,0,0,170,1)).key(0,new MotionProject.Key(2,1,0.5,0,-170,0.5));MotionProject.Key at=p.sample(0,1);assertEquals(0.5,at.x,1e-9);assertEquals(0.75,at.scale,1e-9);assertEquals(180,Math.abs(at.yaw),1e-8);assertEquals(p.json(),MotionProject.parse(p.json()).json());Bitmap a=SceneEngine.render(p.at(0),128,p.base),b=SceneEngine.render(p.at(2),128,p.base);assertFalse(a.sameAs(b));a.recycle();b.recycle();
        try{new MotionProject.Key(-1,0,0,0,0,1);fail();}catch(IllegalArgumentException expected){}try{new MotionProject.Key(1,0,0,0,0,Double.POSITIVE_INFINITY);fail();}catch(IllegalArgumentException expected){}
        MotionProject q=MotionProject.from(single());for(int i=0;i<8;i++)q=q.key(0,new MotionProject.Key(i,0,0,0,i*10,1));try{q.key(0,new MotionProject.Key(9,0,0,0,0,1));fail("Track bound");}catch(IllegalArgumentException expected){}assertEquals(8,q.key(0,new MotionProject.Key(7,0,0,0,45,1)).tracks.get(0).size());
    }
    public void testGlbMotionChunksAndEvidence()throws Exception{
        MotionProject p=MotionActivity.demo();byte[] bytes=GlbWriter.write(p);ByteBuffer b=ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN);assertEquals(0x46546c67,b.getInt());assertEquals(2,b.getInt());assertEquals(bytes.length,b.getInt());int len=b.getInt();assertEquals(0x4e4f534a,b.getInt());byte[] json=new byte[len];b.get(json);JSONObject root=new JSONObject(new String(json,"UTF-8"));assertEquals("2.0",root.getJSONObject("asset").getString("version"));assertEquals(1,root.getJSONArray("animations").length());assertEquals(3,root.getJSONArray("animations").getJSONObject(0).getJSONArray("channels").length());assertEquals(1,root.getJSONArray("nodes").length());int binaryLength=b.getInt();assertEquals(0x004e4942,b.getInt());assertEquals(binaryLength,b.remaining());JSONArray views=root.getJSONArray("bufferViews");for(int i=0;i<views.length();i++){JSONObject v=views.getJSONObject(i);assertEquals(0,v.getInt("byteOffset")%4);assertTrue(v.getInt("byteOffset")+v.getInt("byteLength")<=binaryLength);}
        File dir=getInstrumentation().getTargetContext().getExternalFilesDir(null);try(FileOutputStream out=new FileOutputStream(new File(dir,"motion-v142.glb"))){out.write(bytes);}try(FileOutputStream out=new FileOutputStream(new File(dir,"motion-v142.zip"))){MotionFiles.zip(p,out);}
    }
    public void testImageTrialHeldoutCheckpointAndEvidence()throws Exception{
        ImageLearning.Trial trial=ImageLearning.train();assertEquals(6,trial.report.getInt("training_examples"));assertEquals(3,trial.report.getInt("heldout_examples"));assertTrue(trial.report.toString(),trial.report.getDouble("heldout_rgb_mae")<trial.report.getDouble("baseline_training_mean_rgb_mae"));assertTrue(trial.report.getDouble("heldout_foreground_rgb_mae")<0.03);assertFalse(trial.report.getBoolean("photorealism_qualified"));assertFalse(trial.report.getBoolean("production_activation_authorized"));assertTrue(trial.report.getBoolean("checkpoint_reload_verified"));ImageLearning.Model reloaded=ImageLearning.Model.read(trial.model.bytes());Bitmap a=trial.model.generate("hình cầu màu đỏ"),b=reloaded.generate("HÌNH CẦU MÀU ĐỎ");assertTrue(a.sameAs(b));a.recycle();b.recycle();try{reloaded.generate("ảnh chân dung người thật");fail("Unsupported prompt");}catch(IllegalArgumentException expected){}byte[] broken=trial.model.bytes();broken[0]=0;broken[1]=0;try{ImageLearning.Model.read(broken);fail("Corrupt checkpoint");}catch(IOException expected){}
        try(FileOutputStream out=new FileOutputStream(new File(getInstrumentation().getTargetContext().getExternalFilesDir(null),"image-trial-v142.zip"))){ImageLearning.zip(trial,out);}
    }
    public void testMotionEditorUndoDurabilityAndDocumentExport()throws Exception{
        Context c=getInstrumentation().getTargetContext();MotionActivity a=(MotionActivity)getInstrumentation().startActivitySync(new Intent(c,MotionActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));File export=new File(c.getCacheDir(),"motion-test.zip");
        try{getInstrumentation().runOnMainSync(()->{a.change(MotionProject.from(single()));a.center.setText("0,0,1");a.stroke.performClick();assertEquals(1,a.project.base.items.get(0).strokes.size());a.undo.performClick();assertEquals(0,a.project.base.items.get(0).strokes.size());a.redo.performClick();assertEquals(1,a.project.base.items.get(0).strokes.size());a.keyTime.setText("0");a.saveKey.performClick();a.keyTime.setText("2");a.offset.setText("0.5,0,0");a.yaw.setText("90");a.saveKey.performClick();assertEquals(2,a.project.tracks.get(0).size());a.pending=a.project;a.onActivityResult(1,android.app.Activity.RESULT_OK,new Intent().setData(android.net.Uri.fromFile(export)));});long end=android.os.SystemClock.elapsedRealtime()+20000;while(a.busy&&android.os.SystemClock.elapsedRealtime()<end)android.os.SystemClock.sleep(50);getInstrumentation().waitForIdleSync();assertFalse(a.busy);try(ZipFile z=new ZipFile(export)){assertNotNull(z.getEntry("scene.glb"));assertNotNull(z.getEntry("project.bia-motion.json"));}}
        finally{export.delete();getInstrumentation().runOnMainSync(a::finish);}getInstrumentation().waitForIdleSync();MotionActivity restored=(MotionActivity)getInstrumentation().startActivitySync(new Intent(c,MotionActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));try{assertEquals(1,restored.project.base.items.get(0).strokes.size());assertEquals(2,restored.project.tracks.get(0).size());}finally{getInstrumentation().runOnMainSync(restored::finish);}
    }
    public void testImageLabTrainsGeneratesAndRestores()throws Exception{
        Context c=getInstrumentation().getTargetContext();ImageLabActivity a=(ImageLabActivity)getInstrumentation().startActivitySync(new Intent(c,ImageLabActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));getInstrumentation().runOnMainSync(()->a.train.performClick());long end=android.os.SystemClock.elapsedRealtime()+20000;while(a.busy&&android.os.SystemClock.elapsedRealtime()<end)android.os.SystemClock.sleep(50);getInstrumentation().waitForIdleSync();assertFalse(a.busy);assertNotNull(a.model);assertNotNull(a.trial);getInstrumentation().runOnMainSync(()->{a.generate.performClick();assertNotNull(a.image);assertEquals(64,a.image.getWidth());a.finish();});getInstrumentation().waitForIdleSync();ImageLabActivity b=(ImageLabActivity)getInstrumentation().startActivitySync(new Intent(c,ImageLabActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));try{assertNotNull(b.model);}finally{getInstrumentation().runOnMainSync(b::finish);}
    }
}
