package com.bia.mobile;
import android.test.InstrumentationTestCase;
import android.content.*;
import android.os.SystemClock;
import java.util.*;
import java.io.*;
import java.util.zip.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;
import org.json.*;

public final class ProductStudioTest extends InstrumentationTestCase {
    String spec(String id,String kind){return "BIA_PRODUCT_1\n"+String.join("\n",Arrays.asList(ProductBundle.hex(id),ProductBundle.hex(kind),ProductBundle.hex("Công cụ Việt <script>"),ProductBundle.hex("Nhóm dịch vụ"),ProductBundle.hex("Quản lý dữ liệu trên thiết bị"),ProductBundle.hex("BIA test"),ProductBundle.hex("USD"),ProductBundle.hex("#176b5b")));}
    public void testNativeBundlesAndZipChecksums()throws Exception{
        for(String kind:new String[]{"quote","stock","tasks"}){ProductBundle b=ProductBundle.compile(spec("test-product-1",kind));assertEquals(11,b.files.size());assertFalse(b.files.get("config.js").contains("<script>"));ByteArrayOutputStream out=new ByteArrayOutputStream();b.zip(out);TreeMap<String,String> unpacked=new TreeMap<>();try(ZipInputStream z=new ZipInputStream(new ByteArrayInputStream(out.toByteArray()))){for(ZipEntry e;(e=z.getNextEntry())!=null;){assertFalse(e.getName().contains("/"));ByteArrayOutputStream body=new ByteArrayOutputStream();byte[] chunk=new byte[4096];for(int n;(n=z.read(chunk))!=-1;)body.write(chunk,0,n);unpacked.put(e.getName(),body.toString("UTF-8"));}}assertEquals(12,unpacked.size());JSONObject hashes=new JSONObject(unpacked.remove("MANIFEST.json")).getJSONObject("sha256");for(String name:unpacked.keySet())assertEquals(hashes.getString(name),ProductBundle.hash(unpacked.get(name)));assertEquals(b.files,unpacked);}
        try{ProductBundle.compile(spec("test-product-1","unsupported"));fail("Unsupported accepted");}catch(IllegalArgumentException expected){}
    }
    public void testDurableVersionsAndCorruptionRejection()throws Exception{
        Context c=getInstrumentation().getTargetContext();String name="products-test-"+System.nanoTime()+".db";ProductStore store=new ProductStore(c,name);try{String source=spec("test-product-2","stock");ProductBundle b=ProductBundle.compile(source);long first=store.save("test-product-2","Kho",source,b),second=store.save("test-product-2","Kho",source,b);assertTrue(second>first);store.close();store=new ProductStore(c,name);assertEquals(b.files,store.load(first).files);assertEquals(2,store.list().size());store.getWritableDatabase().execSQL("UPDATE builds SET bundle='{}' WHERE id=?",new Object[]{second});try{store.load(second);fail("Corruption accepted");}catch(IllegalStateException expected){}assertEquals(b.files,store.load(first).files);}finally{store.close();c.deleteDatabase(name);}
    }
    String js(ProductPreviewActivity a,String code)throws Exception{CountDownLatch latch=new CountDownLatch(1);AtomicReference<String> result=new AtomicReference<>();getInstrumentation().runOnMainSync(()->a.web.evaluateJavascript(code,value->{result.set(value);latch.countDown();}));assertTrue("JS callback timeout",latch.await(5,TimeUnit.SECONDS));return result.get();}
    void ready(ProductPreviewActivity a)throws Exception{long until=SystemClock.elapsedRealtime()+15000;while(SystemClock.elapsedRealtime()<until){if("true".equals(js(a,"window.BIA_READY===true")))return;SystemClock.sleep(100);}fail("Generated product did not start");}
    public void testGeneratedProductsRunPersistAndRejectInvalidRows()throws Exception{
        Context c=getInstrumentation().getTargetContext();try(ProductStore store=new ProductStore(c)){for(String kind:new String[]{"quote","stock","tasks"}){String id=UUID.randomUUID().toString(),source=spec(id,kind);long build=store.save(id,"Runtime test",source,ProductBundle.compile(source));ProductPreviewActivity a=(ProductPreviewActivity)getInstrumentation().startActivitySync(new Intent(c,ProductPreviewActivity.class).putExtra("build",build).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));try{ready(a);getInstrumentation().runOnMainSync(()->{assertFalse(a.web.getSettings().getAllowFileAccess());assertTrue(a.web.getSettings().getBlockNetworkLoads());});String fields=kind.equals("quote")?"qty.value='3';price.value='0.10';":kind.equals("stock")?"sku.value='SKU-1';qty.value='0';threshold.value='2';":"due.value='2026-10-03';priority.value='1';document.getElementById('status').value='done';";
            js(a,"document.getElementById('name').value='<img src=x onerror=alert(1)>';"+fields+"document.getElementById('editor').requestSubmit();");assertEquals("1",js(a,"document.getElementById('rows').children.length"));assertEquals("0",js(a,"document.querySelectorAll('img').length"));String summary=js(a,"document.getElementById('summary').textContent");assertTrue(summary,summary.contains(kind.equals("quote")?"0.30":kind.equals("stock")?"1 tồn thấp":"1/1"));js(a,"window.BIA_READY=false;");getInstrumentation().runOnMainSync(()->a.web.reload());ready(a);assertEquals("1",js(a,"document.getElementById('rows').children.length"));
            if(kind.equals("stock")){js(a,"document.getElementById('name').value='Duplicate';sku.value='SKU-1';document.getElementById('editor').requestSubmit();");assertEquals("1",js(a,"document.getElementById('rows').children.length"));assertTrue(js(a,"document.getElementById('message').textContent").contains("Trùng"));}
            js(a,"document.getElementById('qa').click();");assertTrue(js(a,"document.getElementById('message').textContent").contains("4 kiểm tra"));
        }finally{js(a,"Object.keys(localStorage).filter(k=>k.includes('"+id+"')).forEach(k=>localStorage.removeItem(k));");getInstrumentation().runOnMainSync(a::finish);store.delete(build);}}}
    }
    public void testWorkbenchBuildsAndReopensSavedProduct()throws Exception{
        Context c=getInstrumentation().getTargetContext();ProductActivity a=(ProductActivity)getInstrumentation().startActivitySync(new Intent(c,ProductActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));getInstrumentation().runOnMainSync(()->{a.title.setText("Báo giá dịch vụ");a.audience.setText("Nhóm thiết kế");a.brief.setText("Theo dõi dòng báo giá trước thuế");a.author.setText("BIA Product Studio");a.build.performClick();});long until=SystemClock.elapsedRealtime()+15000;while(a.busy&&SystemClock.elapsedRealtime()<until)SystemClock.sleep(100);getInstrumentation().waitForIdleSync();assertTrue(a.result.getText().toString(),a.selected>0);long id=a.selected;try(FileOutputStream out=new FileOutputStream(new File(c.getExternalFilesDir(null),"product-demo.zip"))){a.store.load(id).zip(out);}
        getInstrumentation().runOnMainSync(a::finish);getInstrumentation().waitForIdleSync();ProductActivity reopened=(ProductActivity)getInstrumentation().startActivitySync(new Intent(c,ProductActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));assertEquals(id,reopened.selected);assertEquals("Báo giá dịch vụ",reopened.title.getText().toString());getInstrumentation().runOnMainSync(()->{reopened.store.delete(id);reopened.selected=-1;reopened.finish();});
    }
}
