plugins {
    id "com.android.application"
}

android {
    namespace "com.bia.mobile"
    compileSdk 35

    defaultConfig {
        applicationId "com.bia.mobile"
        minSdk 26
        targetSdk 35
        versionCode 130
        versionName "1.30.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt")
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ["src/main/jniLibs"]
        }
    }
}

dependencies {
}
