plugins {
    id "com.android.application"
}

android {
    namespace "com.bia.mobile"
    compileSdk 35
    useLibrary "android.test.runner"
    useLibrary "android.test.base"
    useLibrary "android.test.mock"

    defaultConfig {
        applicationId "com.bia.mobile"
        minSdk 26
        targetSdk 35
        testInstrumentationRunner "android.test.InstrumentationTestRunner"
        versionCode 142
        versionName "1.42.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt")
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ["src/main/jniLibs"]
        }
    }
}

dependencies {
    implementation "com.squareup.okhttp3:okhttp:4.12.0"
    implementation "com.solanamobile:mobile-wallet-adapter-clientlib:2.0.8"
    implementation "org.bouncycastle:bcprov-jdk15to18:1.86"
}
