package com.bia.mobile;
import android.graphics.*;import org.json.*;import java.io.*;import java.util.*;import java.util.regex.*;import java.text.Normalizer;import java.util.zip.*;

/** Closed-vocabulary image factor learning pilot, not a foundation model or photo generator. */
public final class ImageLearning {
    public static final int SIZE=64,PIXELS=SIZE*SIZE;
    static final String[] SHAPES={"sphere","box","torus"},SHAPE_NAMES={"hình cầu","khối hộp","vòng xuyến"},COLOR_NAMES={"đỏ","xanh lá","xanh dương"};
    static final int[] COLORS={0xffdc634a,0xff48bf88,0xff638dde};
    public static final class Model {
        final float[][] shade=new float[3][PIXELS],alpha=new float[3][PIXELS],palette=new float[3][3];
        final int[] shapeCount=new int[3],colorCount=new int[3];
        public Bitmap generate(String prompt){String normalized=Normalizer.normalize(prompt,Normalizer.Form.NFD).replaceAll("\\p{M}+","").toLowerCase(Locale.ROOT).replace('đ','d').trim().replaceAll("\\s+"," ");Matcher m=Pattern.compile("^(hinh cau|khoi hop|vong xuyen) mau (do|xanh la|xanh duong)$").matcher(normalized);if(!m.matches())throw new IllegalArgumentException("Thử nghiệm chỉ nhận: hình cầu/khối hộp/vòng xuyến màu đỏ/xanh lá/xanh dương");int shape=Arrays.asList("hinh cau","khoi hop","vong xuyen").indexOf(m.group(1)),color=Arrays.asList("do","xanh la","xanh duong").indexOf(m.group(2));return generate(shape,color);}
        Bitmap generate(int shape,int color){if(shapeCount[shape]<1||colorCount[color]<1)throw new IllegalStateException("Chưa học tổ hợp thành phần");int[] pixels=new int[PIXELS];for(int i=0;i<PIXELS;i++){int a=(int)Math.round(alpha[shape][i]*255);pixels[i]=Color.argb(a,channel(palette[color][0]*shade[shape][i]),channel(palette[color][1]*shade[shape][i]),channel(palette[color][2]*shade[shape][i]));}return Bitmap.createBitmap(pixels,SIZE,SIZE,Bitmap.Config.ARGB_8888);}
        public byte[] bytes()throws IOException{ByteArrayOutputStream b=new ByteArrayOutputStream();DataOutputStream d=new DataOutputStream(b);d.writeUTF("BIA_IMAGE_FACTORS_1");d.writeInt(SIZE);for(int i=0;i<3;i++){d.writeInt(shapeCount[i]);d.writeInt(colorCount[i]);for(float v:shade[i])d.writeFloat(v);for(float v:alpha[i])d.writeFloat(v);for(float v:palette[i])d.writeFloat(v);}d.flush();return b.toByteArray();}
        public static Model read(byte[] bytes)throws IOException{if(bytes.length>110000)throw new IOException("Checkpoint quá lớn");DataInputStream d=new DataInputStream(new ByteArrayInputStream(bytes));if(!d.readUTF().equals("BIA_IMAGE_FACTORS_1")||d.readInt()!=SIZE)throw new IOException("Sai checkpoint");Model m=new Model();for(int i=0;i<3;i++){m.shapeCount[i]=d.readInt();m.colorCount[i]=d.readInt();if(m.shapeCount[i]!=2||m.colorCount[i]!=2)throw new IOException("Sai số mẫu");for(int j=0;j<PIXELS;j++)m.shade[i][j]=value(d,1.35f);for(int j=0;j<PIXELS;j++)m.alpha[i][j]=value(d,1);for(int j=0;j<3;j++)m.palette[i][j]=value(d,1);}if(d.available()!=0)throw new IOException("Dữ liệu thừa");return m;}
        static float value(DataInputStream d,float max)throws IOException{float v=d.readFloat();if(!Float.isFinite(v)||v<0||v>max)throw new IOException("Trọng số không hợp lệ");return v;}
    }
    static int channel(double v){return (int)Math.round(Math.max(0,Math.min(1,v))*255);}
    static Bitmap target(int shape,int color)throws Exception{SceneEngine.Item item=new SceneEngine.Item(SHAPES[shape],24,COLORS[color],42,0,0,0,1,1,1,0,0,0,0,true);return SceneEngine.render(new SceneEngine.Scene(Collections.singletonList(item),0.6,0.3,1,-0.5,512,true),SIZE);}
    public static final class Trial {public final Model model;public final JSONObject report;final byte[][] images;Trial(Model m,JSONObject r,byte[][] images){model=m;report=r;this.images=images;}}
    public static Trial train()throws Exception{
        long start=System.nanoTime();Model model=new Model();byte[][] images=new byte[9][];int[][] pixels=new int[9][PIXELS];float[] baseline=new float[PIXELS*3];JSONArray manifest=new JSONArray();
        for(int shape=0;shape<3;shape++)for(int color=0;color<3;color++){if(Thread.currentThread().isInterrupted())throw new InterruptedIOException("Đã dừng thử nghiệm");int id=shape*3+color;Bitmap b=target(shape,color);try{b.getPixels(pixels[id],0,SIZE,0,0,SIZE,SIZE);ByteArrayOutputStream out=new ByteArrayOutputStream();if(!b.compress(Bitmap.CompressFormat.PNG,100,out))throw new IOException("PNG lỗi");images[id]=out.toByteArray();}finally{b.recycle();}boolean train=shape!=color;manifest.put(new JSONObject().put("image","dataset/"+id+".png").put("caption",SHAPE_NAMES[shape]+" màu "+COLOR_NAMES[color]).put("split",train?"train":"heldout").put("sha256",hash(images[id])).put("provenance","BIA native procedural renderer; no external assets"));
            if(!train)continue;float[] rgb={Color.red(COLORS[color])/255f,Color.green(COLORS[color])/255f,Color.blue(COLORS[color])/255f};model.shapeCount[shape]++;model.colorCount[color]++;for(int k=0;k<3;k++)model.palette[color][k]+=rgb[k];for(int i=0;i<PIXELS;i++){int p=pixels[id][i];float a=Color.alpha(p)/255f;model.alpha[shape][i]+=a;float[] observed={Color.red(p)/255f,Color.green(p)/255f,Color.blue(p)/255f};double sum=0;for(int k=0;k<3;k++){sum+=observed[k]/rgb[k];baseline[i*3+k]+=observed[k]/6f;}model.shade[shape][i]+=(float)(sum/3);}
        }
        for(int shape=0;shape<3;shape++){for(int i=0;i<PIXELS;i++){model.alpha[shape][i]/=model.shapeCount[shape];model.shade[shape][i]/=model.shapeCount[shape];}for(int k=0;k<3;k++)model.palette[shape][k]/=model.colorCount[shape];}
        Model reloaded=Model.read(model.bytes());double error=0,baseError=0,fgError=0;long foreground=0;JSONArray perCase=new JSONArray();
        for(int held=0;held<3;held++){Bitmap b=reloaded.generate(held,held);int[] generated=new int[PIXELS];b.getPixels(generated,0,SIZE,0,0,SIZE,SIZE);b.recycle();double local=0;for(int i=0;i<PIXELS;i++){int target=pixels[held*3+held][i],pred=generated[i];int[] a={Color.red(target),Color.green(target),Color.blue(target)},v={Color.red(pred),Color.green(pred),Color.blue(pred)};for(int k=0;k<3;k++){double e=Math.abs(a[k]-v[k])/255.0;local+=e;baseError+=Math.abs(a[k]/255.0-baseline[i*3+k]);if(Color.alpha(target)>0){fgError+=e;foreground++;}}}error+=local;perCase.put(new JSONObject().put("caption",SHAPE_NAMES[held]+" màu "+COLOR_NAMES[held]).put("rgb_mae",local/(PIXELS*3)));}
        double mae=error/(3*PIXELS*3),baselineMae=baseError/(3*PIXELS*3);JSONObject report=new JSONObject().put("schema","BIA_IMAGE_TRIAL_1").put("training_examples",6).put("heldout_examples",3).put("resolution",SIZE).put("method","supervised shade/alpha atlas factor averages plus labelled material colours; fixed camera/light").put("heldout_rgb_mae",mae).put("heldout_foreground_rgb_mae",fgError/Math.max(1,foreground)).put("baseline_training_mean_rgb_mae",baselineMae).put("checkpoint_reload_verified",Arrays.equals(model.bytes(),reloaded.bytes())).put("execution_passed",true).put("closed_domain_improved",mae<baselineMae).put("photorealism_qualified",false).put("open_vocabulary_qualified",false).put("production_activation_authorized",false).put("duration_ms",(System.nanoTime()-start)/1000000).put("cases",perCase).put("dataset",manifest);
        return new Trial(reloaded,report,images);
    }
    static String hash(byte[] bytes)throws Exception{byte[] d=java.security.MessageDigest.getInstance("SHA-256").digest(bytes);StringBuilder b=new StringBuilder();for(byte v:d)b.append(String.format(Locale.ROOT,"%02x",v&255));return b.toString();}
    public static void zip(Trial trial,OutputStream output)throws Exception{try(ZipOutputStream z=new ZipOutputStream(output)){CreativeEngine.entry(z,"model.bia-image",trial.model.bytes());SceneEngine.text(z,"report.json",trial.report.toString(2));for(int i=0;i<trial.images.length;i++)CreativeEngine.entry(z,"dataset/"+i+".png",trial.images[i]);Bitmap b=trial.model.generate("hình cầu màu đỏ");try{z.putNextEntry(new ZipEntry("learned-heldout.png"));if(!b.compress(Bitmap.CompressFormat.PNG,100,z))throw new IOException("PNG lỗi");z.closeEntry();}finally{b.recycle();}SceneEngine.text(z,"README.txt","BIA V142 — thử nghiệm học nhân tố ảnh 64×64, ba hình và ba màu, camera/ánh sáng cố định. Học 6 tổ hợp, đánh giá 3 tổ hợp giữ riêng. Checkpoint chứa trường độ sáng/alpha theo hình và màu từ nhãn; không phải LLM, diffusion hay trọng số bên ngoài.\nĐây là thử nghiệm đóng, không chứng minh ảnh chân thực, mô tả tự do hoặc thiết kế mô hình nền tảng mới. Dữ liệu đều do mã BIA dựng; split và SHA-256 có trong report.json. Có thể chạy lại trên CPU qua nút Phòng thử nghiệm ảnh trong APK. Không dùng kết quả này làm đánh giá chất lượng ảnh thực.\n");}}
}
