package com.bia.mobile;
import android.app.*;import android.os.*;import android.content.*;import android.widget.*;import android.graphics.*;import android.util.AtomicFile;import java.io.*;import java.util.concurrent.*;
public final class ImageLabActivity extends Activity {
    ImageLearning.Model model;ImageLearning.Trial trial;EditText prompt;TextView status;ImageView preview;Button train,generate,export;volatile boolean busy;Bitmap image;final ExecutorService worker=Executors.newSingleThreadExecutor();
    @Override public void onCreate(Bundle b){super.onCreate(b);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setPadding(18,16,18,16);ScrollView scroll=new ScrollView(this);scroll.addView(root);setContentView(scroll);TextView intro=new TextView(this);intro.setText("Phòng thử nghiệm ảnh riêng · V142\nHọc từ ảnh tự dựng 64×64: hình cầu, khối hộp, vòng xuyến; màu đỏ, xanh lá, xanh dương. Chưa phải tạo ảnh chân thực hoặc mô tả tự do.");root.addView(intro);train=new Button(this);train.setText("Tạo dữ liệu và huấn luyện thử trên CPU");root.addView(train);prompt=new EditText(this);prompt.setSingleLine();prompt.setText("hình cầu màu đỏ");root.addView(prompt);generate=new Button(this);generate.setText("Sinh ảnh bằng checkpoint đã học");root.addView(generate);preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);root.addView(preview,new LinearLayout.LayoutParams(-1,500));export=new Button(this);export.setText("Xuất dữ liệu + checkpoint + báo cáo");root.addView(export);status=new TextView(this);root.addView(status);
        train.setOnClickListener(v->runTrial());generate.setOnClickListener(v->{try{if(model==null)throw new IllegalStateException("Cần huấn luyện trước");Bitmap next=model.generate(prompt.getText().toString());preview.setImageBitmap(next);if(image!=null)image.recycle();image=next;status.setText("Ảnh học 64×64 · từ vựng giới hạn · chưa đạt ảnh chân thực");}catch(Exception e){status.setText(e.getMessage());}});export.setOnClickListener(v->{if(trial==null){status.setText("Chạy thử nghiệm trong phiên này để xuất đầy đủ dữ liệu và báo cáo.");return;}startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/zip").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"BIA-image-trial.zip"),1);});
        try{AtomicFile file=new AtomicFile(new File(getFilesDir(),"image-lab-model.bin"));if(file.getBaseFile().exists()){byte[] bytes=file.readFully();model=ImageLearning.Model.read(bytes);status.setText("Đã mở checkpoint thử nghiệm đã học.");}}catch(Exception e){status.setText("Checkpoint lỗi; có thể huấn luyện lại.");}
    }
    void working(boolean b){busy=b;train.setEnabled(!b);generate.setEnabled(!b);export.setEnabled(!b);}
    void runTrial(){working(true);status.setText("Đang tạo dữ liệu, học và đánh giá phần giữ riêng…");worker.execute(()->{ImageLearning.Trial result=null;String error=null;try{result=ImageLearning.train();AtomicFile file=new AtomicFile(new File(getFilesDir(),"image-lab-model.bin"));FileOutputStream out=null;try{out=file.startWrite();out.write(result.model.bytes());file.finishWrite(out);}catch(Exception e){if(out!=null)file.failWrite(out);throw e;}}catch(Exception e){error=e.getMessage();}final ImageLearning.Trial done=result;final String failure=error;runOnUiThread(()->{if(isDestroyed())return;working(false);if(failure!=null){status.setText("Thử nghiệm chưa hoàn thành: "+failure);return;}trial=done;model=done.model;status.setText("Đã học 6 mẫu; đánh giá 3 tổ hợp giữ riêng.\nMAE="+done.report.optDouble("heldout_rgb_mae")+"; baseline="+done.report.optDouble("baseline_training_mean_rgb_mae")+"\nChưa đạt ảnh chân thực; không tự kích hoạt sản xuất.");});});}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;if(trial==null){status.setText("Phiên thử nghiệm đã mất; chạy lại để xuất.");return;}final ImageLearning.Trial captured=trial;final android.net.Uri uri=data.getData();working(true);worker.execute(()->{String msg;try(OutputStream out=getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new IOException("Không mở được tệp");ImageLearning.zip(captured,out);msg="Đã xuất thử nghiệm.";}catch(Exception e){msg="Không hoàn thành: "+e.getMessage();}final String m=msg;runOnUiThread(()->{if(!isDestroyed()){working(false);status.setText(m);}});});}
    @Override protected void onDestroy(){worker.shutdown();preview.setImageDrawable(null);if(image!=null)image.recycle();super.onDestroy();}
}
