package com.bia.mobile;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;import java.util.concurrent.*;

public final class MotionActivity extends Activity {
    MotionProject project,pending;Spinner objects,brush;EditText center,radius,strength,direction,keyTime,offset,yaw,factor;CheckBox mirror,tap;SeekBar timeline;TextView status;ImageView preview;Button stroke,subdivide,saveKey,play,undo,redo;double time;int selected,generation;boolean refreshing,rendering,playing;volatile boolean busy;long playStart;final ExecutorService renderWorker=Executors.newSingleThreadExecutor(),io=Executors.newSingleThreadExecutor();final ArrayDeque<String> past=new ArrayDeque<>(),future=new ArrayDeque<>();final ArrayList<View> controls=new ArrayList<>();Bitmap image;
    @Override public void onCreate(Bundle state){super.onCreate(state);LinearLayout root=new LinearLayout(this);root.setPadding(16,12,16,16);root.setOrientation(1);ScrollView scroll=new ScrollView(this);scroll.addView(root);setContentView(scroll);label(root,"Điêu khắc & hoạt hình · V142\nCọ dùng tọa độ cục bộ; tối đa 24 dấu/vật thể. Chuyển động vật thể, chưa có khung xương. Áp dụng trước khi rời màn hình.");objects=spinner(root,new String[]{"Vật thể"});objects.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int i,long id){if(!refreshing)selected=i;}});
        preview=new ImageView(this);preview.setScaleType(ImageView.ScaleType.FIT_CENTER);preview.setBackgroundColor(0xff253249);root.addView(preview,new LinearLayout.LayoutParams(-1,(int)(300*getResources().getDisplayMetrics().density)));preview.setOnTouchListener((v,e)->{if(!tap.isChecked()||playing||busy||rendering)return false;if(e.getActionMasked()==MotionEvent.ACTION_DOWN){v.getParent().requestDisallowInterceptTouchEvent(true);return true;}if(e.getActionMasked()==MotionEvent.ACTION_UP){v.getParent().requestDisallowInterceptTouchEvent(false);try{int side=Math.min(v.getWidth(),v.getHeight());double u=(e.getX()-(v.getWidth()-side)/2.0)/side,w=(e.getY()-(v.getHeight()-side)/2.0)/side;double[] hit=ScenePicking.pick(project.at(time),project.base,selected,u,w);if(hit==null)throw new IllegalArgumentException("Chạm mặt nhìn thấy của vật thể đang chọn");center.setText(hit[0]+","+hit[1]+","+hit[2]);applyStroke();}catch(Exception ex){error(ex);}v.performClick();return true;}if(e.getActionMasked()==MotionEvent.ACTION_CANCEL)v.getParent().requestDisallowInterceptTouchEvent(false);return true;});
        status=label(root,"");timeline=new SeekBar(this);timeline.setMax(20000);root.addView(timeline);controls.add(timeline);timeline.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){stop();}public void onStopTrackingTouch(SeekBar s){}public void onProgressChanged(SeekBar s,int p,boolean user){if(user){time=p/1000.0;keyTime.setText(Double.toString(time));requestRender();}}});
        play=button(root,"Phát / Dừng");play.setOnClickListener(v->{if(playing){stop();return;}if(project.duration()<=0){status.setText("Cần ít nhất hai keyframe khác thời gian để có chuyển động.");return;}playing=true;time=0;playStart=SystemClock.elapsedRealtime();requestRender();});undo=button(root,"Hoàn tác");undo.setOnClickListener(v->travel(past,future));redo=button(root,"Làm lại");redo.setOnClickListener(v->travel(future,past));
        brush=spinner(root,new String[]{"Đắp / lõm","Kéo theo hướng","Làm mịn"});center=field(root,"Tâm cọ X,Y,Z (cục bộ)","0,0,1");radius=field(root,"Bán kính 0.05–3","0.65");strength=field(root,"Lực −0.3…0.3 (âm để lõm)","0.12");direction=field(root,"Hướng kéo X,Y,Z (−1…1)","0,0,1");mirror=new CheckBox(this);mirror.setText("Đối xứng trục X");root.addView(mirror);controls.add(mirror);tap=new CheckBox(this);tap.setText("Chạm hình để đóng một dấu cọ");root.addView(tap);controls.add(tap);stroke=button(root,"Áp dụng cọ");stroke.setOnClickListener(v->{try{applyStroke();}catch(Exception e){error(e);}});subdivide=button(root,"Chia nhỏ lưới ×4 (tối đa 2 lần)");subdivide.setOnClickListener(v->{try{change(project.sculpt(selected,null,project.base.items.get(selected).subdivisions+1));}catch(Exception e){error(e);}});
        keyTime=field(root,"Thời điểm keyframe 0–20 giây","0");offset=field(root,"Dịch chuyển tương đối X,Y,Z","0,0,0");yaw=field(root,"Xoay thêm trục Y −180…180 độ","0");factor=field(root,"Tỷ lệ kích thước 0.2–2","1");saveKey=button(root,"Ghi / thay keyframe tại thời điểm");saveKey.setOnClickListener(v->{try{double[] d=triple(offset);change(project.key(selected,new MotionProject.Key(number(keyTime),d[0],d[1],d[2],number(yaw),number(factor))));}catch(Exception e){error(e);}});Button clear=button(root,"Xóa track vật thể (có hoàn tác)");clear.setOnClickListener(v->change(project.clear(selected)));
        Button export=button(root,"Xuất ZIP: GLB hoạt hình + dự án + PNG");export.setOnClickListener(v->{stop();pending=project;startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/zip").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"BIA-motion.zip"),1);});Button open=button(root,"Mở dự án / cảnh JSON");open.setOnClickListener(v->{stop();startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),2);});Button sample=button(root,"Mở mẫu điêu khắc và chuyển động");sample.setOnClickListener(v->change(demo()));
        try{String saved=state!=null?state.getString("project"):getIntent().getBooleanExtra("fromScene",false)?getSharedPreferences("motion-transfer",0).getString("scene",null):getPreferences(0).getString("project",null);project=saved==null?demo():MotionProject.parse(saved);if(state!=null&&state.getString("pending")!=null)pending=MotionProject.parse(state.getString("pending"));refresh();}catch(Exception e){project=demo();refresh();error(e);}
    }
    static MotionProject demo(){SceneEngine.Item i=SceneEngine.item("sphere",0xff58bfa7,0,0,0,1);SceneEngine.Scene s=new SceneEngine.Scene(Collections.singletonList(i),0.5,0.25,0.8,-0.8,1024,true);return MotionProject.from(s).sculpt(0,new Sculpt.Stroke("push",0.45,0.3,0.8,0.8,0.25,0,0,1,true),1).key(0,new MotionProject.Key(0,0,0,0,0,1)).key(0,new MotionProject.Key(2,0.6,0.25,0,120,0.8)).key(0,new MotionProject.Key(4,0,0,0,0,1));}
    TextView label(LinearLayout r,String s){TextView v=new TextView(this);v.setText(s);r.addView(v);return v;}Button button(LinearLayout r,String s){Button v=new Button(this);v.setText(s);r.addView(v);controls.add(v);return v;}EditText field(LinearLayout r,String s,String value){label(r,s);EditText v=new EditText(this);v.setSingleLine();v.setText(value);r.addView(v);controls.add(v);return v;}Spinner spinner(LinearLayout r,String[] s){Spinner v=new Spinner(this);v.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,s));r.addView(v);controls.add(v);return v;}double number(EditText e){return Double.parseDouble(e.getText().toString().trim());}double[] triple(EditText e){String[] a=e.getText().toString().split(",",-1);if(a.length!=3)throw new IllegalArgumentException("Nhập ba số ngăn bằng dấu phẩy");return new double[]{Double.parseDouble(a[0].trim()),Double.parseDouble(a[1].trim()),Double.parseDouble(a[2].trim())};}
    void applyStroke(){double[] c=triple(center),d=triple(direction);change(project.sculpt(selected,new Sculpt.Stroke(new String[]{"push","grab","smooth"}[brush.getSelectedItemPosition()],c[0],c[1],c[2],number(radius),number(strength),d[0],d[1],d[2],mirror.isChecked()),project.base.items.get(selected).subdivisions));}
    void stop(){playing=false;}void error(Exception e){status.setText("Không hoàn thành: "+e.getMessage());}void push(ArrayDeque<String> q,String s){if(q.size()>=20)q.removeFirst();q.addLast(s);}void change(MotionProject next){stop();try{if(project!=null&&!project.json().equals(next.json())){push(past,project.json());future.clear();}project=next;refresh();}catch(Exception e){error(e);}}
    void travel(ArrayDeque<String> a,ArrayDeque<String> b){stop();if(a.isEmpty())return;try{MotionProject next=MotionProject.parse(a.peekLast());push(b,project.json());a.removeLast();project=next;refresh();}catch(Exception e){error(e);}}
    void refresh(){selected=Math.min(selected,project.base.items.size()-1);refreshing=true;String[] names=new String[project.base.items.size()];for(int i=0;i<names.length;i++)names[i]=(i+1)+" · "+project.base.items.get(i).kind+" · "+project.tracks.get(i).size()+" key";objects.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names));objects.setSelection(selected);refreshing=false;try{getPreferences(0).edit().putString("project",project.json()).apply();}catch(Exception e){error(e);}requestRender();}
    void requestRender(){generation++;schedule();}void schedule(){if(rendering||isDestroyed()||project==null)return;rendering=true;final int ticket=generation;final MotionProject captured=project;final double t=time;renderWorker.execute(()->{Bitmap b=null;String err=null;try{b=SceneEngine.render(captured.at(t),320,captured.base);}catch(Exception e){err=e.getMessage();}final Bitmap result=b;final String failure=err;runOnUiThread(()->{rendering=false;if(isDestroyed()){if(result!=null)result.recycle();return;}if(ticket!=generation){if(result!=null)result.recycle();schedule();return;}if(result!=null){Bitmap old=image;image=result;preview.setImageBitmap(result);if(old!=null)old.recycle();status.setText(String.format(Locale.ROOT,"%.2f / %.2f giây · %d nét cọ · %d keyframe",t,project.duration(),project.base.items.get(selected).strokes.size(),project.tracks.get(selected).size()));}else{stop();status.setText(failure);}if(playing){time=Math.min(project.duration(),(SystemClock.elapsedRealtime()-playStart)/1000.0);timeline.setProgress((int)(time*1000));if(t>=project.duration())stop();else requestRender();}});});}
    void working(boolean b){busy=b;for(View v:controls)v.setEnabled(!b);}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null){pending=null;return;}final android.net.Uri uri=data.getData();final MotionProject captured=pending;working(true);io.execute(()->{String msg;MotionProject imported=null;try{if(request==1){if(captured==null)throw new IOException("Thiếu dự án xuất");try(OutputStream out=getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new IOException("Không mở được tệp");MotionFiles.zip(captured,out);}msg="Đã xuất dự án.";}else{try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("Không đọc được tệp");ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] chunk=new byte[4096];for(int n;(n=in.read(chunk))!=-1;){if(b.size()+n>MotionProject.MAX_JSON)throw new IOException("Tối đa 128 KB");b.write(chunk,0,n);}imported=MotionProject.parse(b.toString("UTF-8"));}msg="Đã mở dự án.";}}catch(Exception e){msg="Không hoàn thành: "+e.getMessage();}final String m=msg;final MotionProject p=imported;runOnUiThread(()->{if(isDestroyed())return;working(false);pending=null;if(p!=null)change(p);status.setText(m);});});}
    @Override protected void onPause(){stop();super.onPause();}@Override protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);try{b.putString("project",project.json());if(pending!=null)b.putString("pending",pending.json());}catch(Exception ignored){}}@Override protected void onDestroy(){stop();renderWorker.shutdownNow();io.shutdown();preview.setImageDrawable(null);if(image!=null)image.recycle();super.onDestroy();}
}
