package com.bia.mobile;
import android.app.*;
import android.os.*;
import android.content.*;
import android.widget.*;
import java.util.*;
import java.util.concurrent.*;
import org.json.*;

/** Mobile product workbench: build, version, inspect and explicitly export. */
public final class ProductActivity extends Activity {
    ProductStore store;final ExecutorService worker=Executors.newSingleThreadExecutor();
    EditText title,audience,brief,author,accent;Spinner kind,currency;TextView result;Button build,preview,export;
    ArrayList<ProductFields.Field> customFields=new ArrayList<>();TextView fieldsSummary;Button addField;
    String project;long selected=-1,exportBuild=-1;volatile boolean busy;volatile boolean destroyed;
    EditText field(LinearLayout root,String label,String value,boolean multi){TextView t=new TextView(this);t.setText(label);root.addView(t);EditText e=new EditText(this);e.setText(value);e.setSingleLine(!multi);if(multi)e.setMinLines(3);root.addView(e);return e;}
    Button button(LinearLayout root,String label){Button b=new Button(this);b.setText(label);root.addView(b);return b;}
    Spinner spinner(LinearLayout root,String[] items){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,items));root.addView(s);return s;}
    @Override public void onCreate(Bundle state){super.onCreate(state);store=new ProductStore(this);project=UUID.randomUUID().toString();ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setPadding(24,24,24,24);scroll.addView(root);setContentView(scroll);
        TextView intro=new TextView(this);intro.setText("BIA V139 · XƯỞNG SẢN PHẨM\nTừ đặc tả → mã nguồn → xem thử → gói bàn giao. Sản phẩm nhiều chức năng và trường dữ liệu tùy biến; không dùng dịch vụ AI ngoài. Chưa tự đăng bán hay chứng minh có người mua.");root.addView(intro);
        kind=spinner(root,new String[]{"Công cụ báo giá","Quản lý kho nhỏ","Quản lý công việc","Bộ tổng hợp: báo giá + kho + công việc"});title=field(root,"Tên sản phẩm", "",false);audience=field(root,"Khách hàng mục tiêu", "",false);brief=field(root,"Vấn đề và yêu cầu (mô tả; không tự sinh tính năng ngoài loại đã chọn)","",true);author=field(root,"Tên người tạo / thương hiệu","",false);currency=spinner(root,new String[]{"VND","USD","EUR"});accent=field(root,"Màu thương hiệu #RRGGBB","#176b5b",false);
        fieldsSummary=new TextView(this);root.addView(fieldsSummary);fieldsSummary.setOnClickListener(v->manageFields());addField=button(root,"Thêm trường dữ liệu");addField.setOnClickListener(v->{if(!busy)editField(-1);});
        button(root,"Sao chép cấu hình thành sản phẩm mới").setOnClickListener(v->{if(busy)return;project=UUID.randomUUID().toString();selected=-1;controls(false);persistDraft();result.setText("Đã tạo bản sao cấu hình với ID mới. Dữ liệu sử dụng của bản cũ không tự chuyển sang bản mới.");});
        build=button(root,"Tạo mã & lưu phiên bản");build.setOnClickListener(v->generate());preview=button(root,"Xem thử phiên bản đã tạo");preview.setOnClickListener(v->{if(selected>0)startActivity(new Intent(this,ProductPreviewActivity.class).putExtra("build",selected));});export=button(root,"Xuất ZIP bàn giao phiên bản đã tạo");export.setOnClickListener(v->{if(selected>0){exportBuild=selected;persistDraft();startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/zip").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"BIA-product-"+selected+".zip"),138);}});
        button(root,"Mở / quản lý phiên bản đã lưu").setOnClickListener(v->versions());button(root,"Tạo sản phẩm mới").setOnClickListener(v->{if(busy)return;project=UUID.randomUUID().toString();selected=-1;customFields.clear();renderFields();title.setText("");audience.setText("");brief.setText("");result.setText("Sản phẩm mới. Điền đặc tả rồi tạo mã.");controls(false);persistDraft();});result=new TextView(this);result.setTextIsSelectable(true);root.addView(result);restoreDraft();renderFields();controls(false);if(selected>0)result.setText("Có phiên bản đã lưu #"+selected+". Thay đổi biểu mẫu chỉ được áp dụng khi tạo phiên bản mới.");
    }
    String spec(){String base="BIA_PRODUCT_1\n"+String.join("\n",Arrays.asList(ProductBundle.hex(project),ProductBundle.hex(new String[]{"quote","stock","tasks","suite"}[kind.getSelectedItemPosition()]),ProductBundle.hex(title.getText().toString().trim()),ProductBundle.hex(audience.getText().toString().trim()),ProductBundle.hex(brief.getText().toString().trim()),ProductBundle.hex(author.getText().toString().trim()),ProductBundle.hex(currency.getSelectedItem().toString()),ProductBundle.hex(accent.getText().toString().trim())));return ProductFields.append(base,customFields);}
    void applySpec(String spec){ArrayList<ProductFields.Field> parsed=ProductFields.parse(spec);String[] a=spec.split("\n");for(int i=1;i<=8;i++)a[i]=ProductBundle.unhex(a[i]);int k=Arrays.asList("quote","stock","tasks","suite").indexOf(a[2]),money=Arrays.asList("VND","USD","EUR").indexOf(a[7]);if(k<0||money<0||!a[1].matches("[a-zA-Z0-9-]{8,64}"))throw new IllegalArgumentException("Đặc tả hỏng");project=a[1];kind.setSelection(k);title.setText(a[3]);audience.setText(a[4]);brief.setText(a[5]);author.setText(a[6]);currency.setSelection(money);accent.setText(a[8]);customFields=parsed;renderFields();}
    void renderFields(){if(fieldsSummary==null)return;StringBuilder s=new StringBuilder("Trường bổ sung (áp dụng cho mọi chức năng):\n");for(ProductFields.Field f:customFields)s.append("• ").append(f.label).append(" · ").append(f.kind).append(f.required?" · bắt buộc":" · tùy chọn").append('\n');s.append("Chạm để sửa/xóa trường. ID được giữ khi sửa.");fieldsSummary.setText(s);}
    void manageFields(){if(busy||customFields.isEmpty())return;String[] items=new String[customFields.size()];for(int i=0;i<items.length;i++)items[i]=customFields.get(i).label;new AlertDialog.Builder(this).setTitle("Sửa trường").setItems(items,(d,w)->editField(w)).show();}
    void editField(int index){if(index<0&&customFields.size()>=12){result.setText("Tối đa 12 trường");return;}ProductFields.Field old=index<0?null:customFields.get(index);LinearLayout l=new LinearLayout(this);l.setOrientation(1);l.setPadding(24,12,24,12);EditText label=field(l,"Tên trường",old==null?"":old.label,false);Spinner type=spinner(l,new String[]{"Văn bản","Số thập phân","Ngày","Danh sách chọn"});String[] types={"text","number","date","choice"};if(old!=null)type.setSelection(Arrays.asList(types).indexOf(old.kind));CheckBox required=new CheckBox(this);required.setText("Bắt buộc nhập");required.setChecked(old!=null&&old.required);l.addView(required);EditText options=field(l,"Giá trị lựa chọn, ngăn cách bằng dấu phẩy (tối đa 12)",old==null?"":old.options,false);
        AlertDialog dialog=new AlertDialog.Builder(this).setTitle(old==null?"Thêm trường":"Sửa trường").setView(l).setPositiveButton("Lưu",null).setNegativeButton("Hủy",null).setNeutralButton(old==null?"":"Xóa",(d,w)->{if(index>=0){customFields.remove(index);renderFields();persistDraft();}}).create();dialog.setOnShowListener(v->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(x->{String name=label.getText().toString().trim(),t=types[type.getSelectedItemPosition()],list="";if(name.isEmpty()||name.codePointCount(0,name.length())>60){label.setError("Cần tên 1–60 ký tự");return;}if(t.equals("choice")){String[] a=options.getText().toString().split(",",-1);HashSet<String> seen=new HashSet<>();ArrayList<String> values=new ArrayList<>();for(String item:a){item=item.trim();if(item.isEmpty()||item.length()>60||!seen.add(item)){options.setError("Giá trị rỗng/trùng/quá dài");return;}values.add(item);}if(values.size()>12){options.setError("Tối đa 12 giá trị");return;}list=String.join(",",values);}ProductFields.Field f=new ProductFields.Field(old==null?"f-"+UUID.randomUUID():old.id,name,t,required.isChecked(),list);if(index<0)customFields.add(f);else customFields.set(index,f);renderFields();persistDraft();dialog.dismiss();}));dialog.show();}
    void controls(boolean value){busy=value;build.setEnabled(!value);preview.setEnabled(!value&&selected>0);export.setEnabled(!value&&selected>0);for(EditText e:new EditText[]{title,audience,brief,author,accent})e.setEnabled(!value);kind.setEnabled(!value);currency.setEnabled(!value);addField.setEnabled(!value);}
    void generate(){if(busy)return;final String source=spec(),id=project,name=title.getText().toString();persistDraft();controls(true);result.setText("Đang tạo mã nguồn…");worker.execute(()->{try{ProductBundle b=ProductBundle.compile(source);long saved=store.save(id,name,source,b);runOnUiThread(()->{if(destroyed)return;selected=saved;controls(false);persistDraft();result.setText("Đã lưu phiên bản #"+saved+"\n11 tệp nguồn/hướng dẫn + manifest SHA-256 khi xuất ZIP.\nĐã kiểm tra đặc tả và cấu trúc gói. Cần xem thử và nghiệm thu với khách trước khi bán.\n\n"+b.files.get("SALES-DRAFT.md"));});}catch(Exception e){runOnUiThread(()->{if(!destroyed){controls(false);result.setText("Chưa tạo: "+e.getMessage());}});}});}
    void versions(){if(busy)return;ArrayList<String[]> list=store.list();if(list.isEmpty()){result.setText("Chưa có phiên bản");return;}String[] labels=new String[list.size()];for(int i=0;i<labels.length;i++)labels[i]=list.get(i)[1];new AlertDialog.Builder(this).setTitle("Phiên bản đã lưu").setItems(labels,(d,w)->{long id=Long.parseLong(list.get(w)[0]);new AlertDialog.Builder(this).setTitle(labels[w]).setPositiveButton("Mở",(x,y)->{try{ProductBundle b=store.load(id);applySpec(b.files.get("SPEC.bia"));selected=id;controls(false);persistDraft();result.setText("Đã mở #"+id+". Tạo lại sẽ lưu phiên bản mới, không sửa bản cũ.\n\n"+b.files.get("README.md"));}catch(Exception e){result.setText(e.getMessage());}}).setNegativeButton("Đóng",null).setNeutralButton("Xóa bản này",(x,y)->new AlertDialog.Builder(this).setMessage("Xóa phiên bản #"+id+"? Hãy xuất ZIP trước nếu cần giữ.").setPositiveButton("Xóa",(a,b)->{store.delete(id);if(selected==id)selected=-1;controls(false);persistDraft();}).setNegativeButton("Hủy",null).show()).show();}).show();}
    void persistDraft(){if(title!=null)getSharedPreferences("product-draft",MODE_PRIVATE).edit().putString("spec",spec()).putLong("selected",selected).putLong("export",exportBuild).apply();}
    void restoreDraft(){android.content.SharedPreferences p=getSharedPreferences("product-draft",MODE_PRIVATE);try{String s=p.getString("spec","");if(!s.isEmpty())applySpec(s);selected=p.getLong("selected",-1);exportBuild=p.getLong("export",-1);if(selected>0)store.load(selected);}catch(Exception e){selected=-1;project=UUID.randomUUID().toString();result.setText("Bản nháp không đọc được; có thể mở phiên bản từ danh sách.");}}
    @Override protected void onPause(){persistDraft();super.onPause();}
    @Override protected void onActivityResult(int code,int status,Intent data){super.onActivityResult(code,status,data);if(code==138 && status==RESULT_OK && data!=null && data.getData()!=null){final long id=exportBuild;final android.net.Uri uri=data.getData();controls(true);worker.execute(()->{try{ProductBundle b=store.load(id);try(java.io.OutputStream out=getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new java.io.IOException("Không mở được tệp");b.zip(out);}runOnUiThread(()->{if(!destroyed){controls(false);result.setText("Đã xuất ZIP phiên bản #"+id+". Giải nén toàn bộ và mở index.html. Đây là gói bàn giao, chưa đăng bán.");}});}catch(Exception e){runOnUiThread(()->{if(!destroyed){controls(false);result.setText("Xuất không thành công; xóa tệp dở nếu có. "+e.getMessage());}});}});}}
    @Override protected void onDestroy(){destroyed=true;worker.execute(store::close);worker.shutdown();super.onDestroy();}
}
