package com.bia.mobile;
import android.app.*;
import android.os.*;
import android.content.*;
import android.widget.*;
import java.util.*;
import java.util.concurrent.*;
import org.json.*;

/** Mobile product workbench: build, version, inspect and explicitly export. */
public final class ProductActivity extends Activity {
    ProductStore store;final ExecutorService worker=Executors.newSingleThreadExecutor();
    EditText title,audience,brief,author,accent;Spinner kind,currency;TextView result;Button build,preview,export;
    String project;long selected=-1,exportBuild=-1;volatile boolean busy;volatile boolean destroyed;
    EditText field(LinearLayout root,String label,String value,boolean multi){TextView t=new TextView(this);t.setText(label);root.addView(t);EditText e=new EditText(this);e.setText(value);e.setSingleLine(!multi);if(multi)e.setMinLines(3);root.addView(e);return e;}
    Button button(LinearLayout root,String label){Button b=new Button(this);b.setText(label);root.addView(b);return b;}
    Spinner spinner(LinearLayout root,String[] items){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,items));root.addView(s);return s;}
    @Override public void onCreate(Bundle state){super.onCreate(state);store=new ProductStore(this);project=UUID.randomUUID().toString();ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setPadding(24,24,24,24);scroll.addView(root);setContentView(scroll);
        TextView intro=new TextView(this);intro.setText("BIA V138 · XƯỞNG SẢN PHẨM\nTừ đặc tả → mã nguồn → xem thử → gói bàn giao. Sinh mã có cấu trúc cho 3 loại công cụ; không dùng dịch vụ AI ngoài. Chưa tự đăng bán hay chứng minh có người mua.");root.addView(intro);
        kind=spinner(root,new String[]{"Công cụ báo giá","Quản lý kho nhỏ","Quản lý công việc"});title=field(root,"Tên sản phẩm", "",false);audience=field(root,"Khách hàng mục tiêu", "",false);brief=field(root,"Vấn đề và yêu cầu (mô tả; không tự sinh tính năng ngoài loại đã chọn)","",true);author=field(root,"Tên người tạo / thương hiệu","",false);currency=spinner(root,new String[]{"VND","USD","EUR"});accent=field(root,"Màu thương hiệu #RRGGBB","#176b5b",false);
        build=button(root,"Tạo mã & lưu phiên bản");build.setOnClickListener(v->generate());preview=button(root,"Xem thử phiên bản đã tạo");preview.setOnClickListener(v->{if(selected>0)startActivity(new Intent(this,ProductPreviewActivity.class).putExtra("build",selected));});export=button(root,"Xuất ZIP bàn giao phiên bản đã tạo");export.setOnClickListener(v->{if(selected>0){exportBuild=selected;persistDraft();startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/zip").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"BIA-product-"+selected+".zip"),138);}});
        button(root,"Mở / quản lý phiên bản đã lưu").setOnClickListener(v->versions());button(root,"Tạo sản phẩm mới").setOnClickListener(v->{if(busy)return;project=UUID.randomUUID().toString();selected=-1;title.setText("");audience.setText("");brief.setText("");result.setText("Sản phẩm mới. Điền đặc tả rồi tạo mã.");controls(false);persistDraft();});result=new TextView(this);result.setTextIsSelectable(true);root.addView(result);restoreDraft();controls(false);if(selected>0)result.setText("Có phiên bản đã lưu #"+selected+". Thay đổi biểu mẫu chỉ được áp dụng khi tạo phiên bản mới.");
    }
    String spec(){return "BIA_PRODUCT_1\n"+String.join("\n",Arrays.asList(ProductBundle.hex(project),ProductBundle.hex(new String[]{"quote","stock","tasks"}[kind.getSelectedItemPosition()]),ProductBundle.hex(title.getText().toString().trim()),ProductBundle.hex(audience.getText().toString().trim()),ProductBundle.hex(brief.getText().toString().trim()),ProductBundle.hex(author.getText().toString().trim()),ProductBundle.hex(currency.getSelectedItem().toString()),ProductBundle.hex(accent.getText().toString().trim())));}
    void applySpec(String spec){String[] a=spec.split("\n");if(a.length!=9 || !a[0].equals("BIA_PRODUCT_1"))throw new IllegalArgumentException("Đặc tả hỏng");for(int i=1;i<a.length;i++)a[i]=ProductBundle.unhex(a[i]);project=a[1];kind.setSelection(Arrays.asList("quote","stock","tasks").indexOf(a[2]));title.setText(a[3]);audience.setText(a[4]);brief.setText(a[5]);author.setText(a[6]);currency.setSelection(Arrays.asList("VND","USD","EUR").indexOf(a[7]));accent.setText(a[8]);}
    void controls(boolean value){busy=value;build.setEnabled(!value);preview.setEnabled(!value&&selected>0);export.setEnabled(!value&&selected>0);for(EditText e:new EditText[]{title,audience,brief,author,accent})e.setEnabled(!value);kind.setEnabled(!value);currency.setEnabled(!value);}
    void generate(){if(busy)return;final String source=spec(),id=project,name=title.getText().toString();persistDraft();controls(true);result.setText("Đang tạo mã nguồn…");worker.execute(()->{try{ProductBundle b=ProductBundle.compile(source);long saved=store.save(id,name,source,b);runOnUiThread(()->{if(destroyed)return;selected=saved;controls(false);persistDraft();result.setText("Đã lưu phiên bản #"+saved+"\n11 tệp nguồn/hướng dẫn + manifest SHA-256 khi xuất ZIP.\nĐã kiểm tra đặc tả và cấu trúc gói. Cần xem thử và nghiệm thu với khách trước khi bán.\n\n"+b.files.get("SALES-DRAFT.md"));});}catch(Exception e){runOnUiThread(()->{if(!destroyed){controls(false);result.setText("Chưa tạo: "+e.getMessage());}});}});}
    void versions(){if(busy)return;ArrayList<String[]> list=store.list();if(list.isEmpty()){result.setText("Chưa có phiên bản");return;}String[] labels=new String[list.size()];for(int i=0;i<labels.length;i++)labels[i]=list.get(i)[1];new AlertDialog.Builder(this).setTitle("Phiên bản đã lưu").setItems(labels,(d,w)->{long id=Long.parseLong(list.get(w)[0]);new AlertDialog.Builder(this).setTitle(labels[w]).setPositiveButton("Mở",(x,y)->{try{ProductBundle b=store.load(id);applySpec(b.files.get("SPEC.bia"));selected=id;controls(false);persistDraft();result.setText("Đã mở #"+id+". Tạo lại sẽ lưu phiên bản mới, không sửa bản cũ.\n\n"+b.files.get("README.md"));}catch(Exception e){result.setText(e.getMessage());}}).setNegativeButton("Đóng",null).setNeutralButton("Xóa bản này",(x,y)->new AlertDialog.Builder(this).setMessage("Xóa phiên bản #"+id+"? Hãy xuất ZIP trước nếu cần giữ.").setPositiveButton("Xóa",(a,b)->{store.delete(id);if(selected==id)selected=-1;controls(false);persistDraft();}).setNegativeButton("Hủy",null).show()).show();}).show();}
    void persistDraft(){if(title!=null)getSharedPreferences("product-draft",MODE_PRIVATE).edit().putString("spec",spec()).putLong("selected",selected).putLong("export",exportBuild).apply();}
    void restoreDraft(){android.content.SharedPreferences p=getSharedPreferences("product-draft",MODE_PRIVATE);try{String s=p.getString("spec","");if(!s.isEmpty())applySpec(s);selected=p.getLong("selected",-1);exportBuild=p.getLong("export",-1);if(selected>0)store.load(selected);}catch(Exception e){selected=-1;project=UUID.randomUUID().toString();result.setText("Bản nháp không đọc được; có thể mở phiên bản từ danh sách.");}}
    @Override protected void onPause(){persistDraft();super.onPause();}
    @Override protected void onActivityResult(int code,int status,Intent data){super.onActivityResult(code,status,data);if(code==138 && status==RESULT_OK && data!=null && data.getData()!=null){final long id=exportBuild;final android.net.Uri uri=data.getData();controls(true);worker.execute(()->{try{ProductBundle b=store.load(id);try(java.io.OutputStream out=getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new java.io.IOException("Không mở được tệp");b.zip(out);}runOnUiThread(()->{if(!destroyed){controls(false);result.setText("Đã xuất ZIP phiên bản #"+id+". Giải nén toàn bộ và mở index.html. Đây là gói bàn giao, chưa đăng bán.");}});}catch(Exception e){runOnUiThread(()->{if(!destroyed){controls(false);result.setText("Xuất không thành công; xóa tệp dở nếu có. "+e.getMessage());}});}});}}
    @Override protected void onDestroy(){destroyed=true;worker.execute(store::close);worker.shutdown();super.onDestroy();}
}
