package com.bia.mobile;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

/** Scene editing is local; external file writes only follow the system document picker. */
public final class SceneActivity extends Activity {
    SceneEngine.Scene scene,pending;Spinner objects,kind,resolution;EditText color,detail,seed,position,scale,rotation,gloss,light;
    CheckBox smooth,transparent;Button apply,add,duplicate,remove,undo,redo,export,open;TextView status,renderStatus;Preview preview;
    final ArrayList<View> controls=new ArrayList<>();final ArrayDeque<String> history=new ArrayDeque<>(),future=new ArrayDeque<>();
    final ExecutorService io=Executors.newSingleThreadExecutor(),renderer=Executors.newSingleThreadExecutor();
    boolean selecting,rendering;volatile boolean busy;int selected,generation;Bitmap image;
    @Override public void onCreate(Bundle state){super.onCreate(state);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setPadding(18,12,18,16);ScrollView scroll=new ScrollView(this);scroll.addView(root);setContentView(scroll);
        label(root,"Xưởng cảnh 3D · V141\nGhép tối đa 12 vật thể / 30.000 tam giác. Kéo để xoay; chụm hai ngón để thu phóng. Áp dụng vật thể trước khi chuyển lựa chọn.");
        objects=spinner(root,new String[]{"Vật thể"});objects.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int i,long id){if(!selecting&&scene!=null&&i<scene.items.size()){selected=i;fillItem();}}});
        preview=new Preview();root.addView(preview,new LinearLayout.LayoutParams(-1,(int)(300*getResources().getDisplayMetrics().density)));renderStatus=label(root,"Đang dựng ảnh…");
        Button motion=button(root,"Điêu khắc & hoạt hình");motion.setOnClickListener(v->{try{getSharedPreferences("motion-transfer",0).edit().putString("scene",scene.json()).commit();startActivity(new Intent(this,MotionActivity.class).putExtra("fromScene",true));}catch(Exception e){error(e);}});
        Button fit=button(root,"Góc nhìn mặc định");fit.setOnClickListener(v->change(scene.camera(0.65,0.35,1)));
        undo=button(root,"Hoàn tác");undo.setOnClickListener(v->travel(history,future));redo=button(root,"Làm lại");redo.setOnClickListener(v->travel(future,history));
        export=button(root,"Xuất cảnh: OBJ + MTL + STL + PNG");export.setOnClickListener(v->{try{applyEditor();pending=scene;startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/zip").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"BIA-scene.zip"),1);}catch(Exception e){error(e);}});
        open=button(root,"Mở cảnh JSON / mô hình V140");open.setOnClickListener(v->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),2));
        status=label(root,"");kind=spinner(root,new String[]{"Khối hộp","Hình cầu","Bình trang trí kín","Hình trụ","Hình nón","Vòng xuyến"});
        color=field(root,"Màu #RRGGBB","#38B9A0");detail=field(root,"Độ chi tiết 8–48","24");seed=field(root,"Seed (số nguyên)","42");position=field(root,"Vị trí X,Y,Z (−20…20)","0,0,0");scale=field(root,"Co giãn X,Y,Z (0.05…5)","1,1,1");rotation=field(root,"Xoay X,Y,Z (độ −360…360)","0,0,0");gloss=field(root,"Độ bóng minh họa 0…1","0.45");smooth=new CheckBox(this);smooth.setText("Làm mịn ánh sáng bề mặt");root.addView(smooth);controls.add(smooth);
        apply=button(root,"Áp dụng vật thể và thiết lập ảnh");apply.setOnClickListener(v->{try{applyEditor();}catch(Exception e){error(e);}});
        add=button(root,"Thêm vật thể từ thông số trên");add.setOnClickListener(v->{try{ArrayList<SceneEngine.Item> items=new ArrayList<>(scene.items);items.add(readItem());SceneEngine.Scene candidate=withSettings(items);selected=items.size()-1;change(candidate);}catch(Exception e){error(e);}});
        duplicate=button(root,"Nhân bản vật thể đã lưu");duplicate.setOnClickListener(v->{try{ArrayList<SceneEngine.Item> items=new ArrayList<>(scene.items);items.add(items.get(selected));SceneEngine.Scene candidate=withSettings(items);selected=items.size()-1;change(candidate);status.setText("Đã nhân bản tại cùng vị trí. Đổi vị trí rồi Áp dụng để tách hai vật thể.");}catch(Exception e){error(e);}});
        remove=button(root,"Xóa vật thể đang chọn");remove.setOnClickListener(v->{try{ArrayList<SceneEngine.Item> items=new ArrayList<>(scene.items);items.remove(selected);change(withSettings(items));}catch(Exception e){error(e);}});
        resolution=spinner(root,new String[]{"PNG 512px","PNG 1024px","PNG 2048px"});transparent=new CheckBox(this);transparent.setText("Xuất PNG nền trong suốt");root.addView(transparent);controls.add(transparent);light=field(root,"Hướng ánh sáng (độ −180…180)","-45");
        Button sample=button(root,"Mở cảnh mẫu bốn vật thể (có thể hoàn tác)");sample.setOnClickListener(v->change(SceneEngine.sample()));
        try{String saved=state!=null?state.getString("scene"):getPreferences(0).getString("scene",null);scene=saved==null?SceneEngine.sample():SceneEngine.Scene.parse(saved);if(state!=null){selected=state.getInt("selected",0);if(state.getString("pending")!=null)pending=SceneEngine.Scene.parse(state.getString("pending"));}refresh();}catch(Exception e){scene=SceneEngine.sample();refresh();status.setText("Bản lưu không hợp lệ; mở cảnh mẫu.");}
    }
    TextView label(LinearLayout root,String text){TextView t=new TextView(this);t.setText(text);root.addView(t);return t;}
    EditText field(LinearLayout root,String label,String initial){label(root,label);EditText e=new EditText(this);e.setSingleLine();e.setText(initial);root.addView(e);controls.add(e);return e;}
    Spinner spinner(LinearLayout root,String[] labels){Spinner s=new Spinner(this);s.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels));root.addView(s);controls.add(s);return s;}
    Button button(LinearLayout root,String label){Button b=new Button(this);b.setText(label);root.addView(b);controls.add(b);return b;}
    double number(EditText e){return Double.parseDouble(e.getText().toString().trim());}
    double[] triple(EditText e){String[] parts=e.getText().toString().trim().split(",",-1);if(parts.length!=3)throw new IllegalArgumentException("Nhập ba số, ngăn bằng dấu phẩy; số thập phân dùng dấu chấm");return new double[]{Double.parseDouble(parts[0].trim()),Double.parseDouble(parts[1].trim()),Double.parseDouble(parts[2].trim())};}
    SceneEngine.Item readItem(){String c=color.getText().toString().trim();if(!c.matches("#[0-9a-fA-F]{6}"))throw new IllegalArgumentException("Màu phải là #RRGGBB");double[] p=triple(position),s=triple(scale),r=triple(rotation);return new SceneEngine.Item(SceneEngine.KINDS[kind.getSelectedItemPosition()],Integer.parseInt(detail.getText().toString().trim()),Color.parseColor(c),Long.parseLong(seed.getText().toString().trim()),p[0],p[1],p[2],s[0],s[1],s[2],r[0],r[1],r[2],number(gloss),smooth.isChecked()).geometry(scene.items.get(selected).strokes,scene.items.get(selected).subdivisions);}
    SceneEngine.Scene withSettings(List<SceneEngine.Item> items){return new SceneEngine.Scene(items,scene.yaw,scene.pitch,scene.zoom,Math.toRadians(number(light)),new int[]{512,1024,2048}[resolution.getSelectedItemPosition()],transparent.isChecked());}
    void applyEditor(){ArrayList<SceneEngine.Item> items=new ArrayList<>(scene.items);items.set(selected,readItem());change(withSettings(items));}
    void error(Exception e){status.setText("Không thay đổi cảnh: "+e.getMessage());}
    void push(ArrayDeque<String> stack,String value){if(stack.size()>=20)stack.removeFirst();stack.addLast(value);}
    void change(SceneEngine.Scene next){try{if(scene!=null&&!scene.json().equals(next.json())){push(history,scene.json());future.clear();}scene=next;refresh();}catch(Exception e){error(e);}}
    void travel(ArrayDeque<String> from,ArrayDeque<String> to){if(from.isEmpty())return;try{SceneEngine.Scene next=SceneEngine.Scene.parse(from.peekLast());push(to,scene.json());from.removeLast();scene=next;refresh();}catch(Exception e){error(e);}}
    void persist(){try{getPreferences(0).edit().putString("scene",scene.json()).apply();}catch(Exception e){error(e);}}
    String tripleText(double a,double b,double c){return a+","+b+","+c;}
    void fillItem(){SceneEngine.Item i=scene.items.get(selected);kind.setSelection(Arrays.asList(SceneEngine.KINDS).indexOf(i.kind));color.setText(String.format(Locale.ROOT,"#%06X",i.color&0xffffff));detail.setText(Integer.toString(i.detail));seed.setText(Long.toString(i.seed));position.setText(tripleText(i.x,i.y,i.z));scale.setText(tripleText(i.sx,i.sy,i.sz));rotation.setText(tripleText(i.rx,i.ry,i.rz));gloss.setText(Double.toString(i.gloss));smooth.setChecked(i.smooth);}
    void refresh(){selected=Math.max(0,Math.min(selected,scene.items.size()-1));selecting=true;String[] labels=new String[scene.items.size()];int triangles=0;for(int i=0;i<labels.length;i++){labels[i]=(i+1)+" · "+scene.items.get(i).kind;triangles+=scene.items.get(i).triangles();}objects.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels));objects.setSelection(selected);selecting=false;fillItem();resolution.setSelection(scene.size==512?0:scene.size==1024?1:2);transparent.setChecked(scene.transparent);light.setText(Double.toString(Math.toDegrees(scene.light)));status.setText(labels.length+" vật thể · "+triangles+" tam giác · đã lưu tham số");undo.setEnabled(!busy&&!history.isEmpty());redo.setEnabled(!busy&&!future.isEmpty());persist();requestRender();}
    void requestRender(){generation++;scheduleRender();}
    void scheduleRender(){if(rendering||isDestroyed()||scene==null)return;rendering=true;final int ticket=generation;final SceneEngine.Scene captured=scene;renderStatus.setText("Đang dựng xem trước…");renderer.execute(()->{Bitmap result=null;String error=null;try{result=SceneEngine.render(captured,384);}catch(Exception e){error=e.getMessage();}final Bitmap ready=result;final String failure=error;runOnUiThread(()->{rendering=false;if(isDestroyed()){if(ready!=null)ready.recycle();return;}if(ticket!=generation){if(ready!=null)ready.recycle();scheduleRender();return;}if(ready!=null){Bitmap old=image;image=ready;preview.invalidate();if(old!=null)old.recycle();renderStatus.setText("Góc nhìn hiện tại sẽ được dùng khi xuất PNG.");}else renderStatus.setText("Lỗi dựng ảnh: "+failure);});});}
    void working(boolean value){busy=value;for(View v:controls)v.setEnabled(!value);undo.setEnabled(!value&&!history.isEmpty());redo.setEnabled(!value&&!future.isEmpty());}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null){pending=null;return;}final android.net.Uri uri=data.getData();final SceneEngine.Scene captured=pending;working(true);status.setText("Đang xử lý tệp…");io.execute(()->{SceneEngine.Scene imported=null;String msg;try{if(request==1){if(captured==null)throw new IOException("Thiếu cảnh xuất; vui lòng xuất lại");try(OutputStream out=getContentResolver().openOutputStream(uri,"wt")){if(out==null)throw new IOException("Không mở được tệp");SceneEngine.zip(captured,out);}msg="Đã xuất cảnh và ảnh.";}else{try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("Không đọc được tệp");ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] chunk=new byte[4096];for(int n;(n=in.read(chunk))!=-1;){if(b.size()+n>SceneEngine.MAX_JSON)throw new IOException("Cảnh tối đa 64 KB");b.write(chunk,0,n);}imported=SceneEngine.Scene.parse(b.toString("UTF-8"));}msg="Đã mở cảnh.";}}catch(Exception e){msg="Không hoàn thành: "+e.getMessage();}final SceneEngine.Scene loaded=imported;final String message=msg;runOnUiThread(()->{if(isDestroyed())return;working(false);pending=null;if(loaded!=null)change(loaded);status.setText(message);});});}
    @Override protected void onSaveInstanceState(Bundle out){super.onSaveInstanceState(out);try{out.putString("scene",scene.json());out.putInt("selected",selected);if(pending!=null)out.putString("pending",pending.json());}catch(Exception ignored){}}
    @Override protected void onDestroy(){renderer.shutdownNow();io.shutdown();if(image!=null){image.recycle();image=null;}super.onDestroy();}
    final class Preview extends View {
        float x,y;final Paint paint=new Paint(Paint.FILTER_BITMAP_FLAG);final ScaleGestureDetector pinch;
        Preview(){super(SceneActivity.this);setContentDescription("Cảnh 3D: kéo để xoay, hai ngón thu phóng");pinch=new ScaleGestureDetector(SceneActivity.this,new ScaleGestureDetector.SimpleOnScaleGestureListener(){@Override public boolean onScale(ScaleGestureDetector d){scene=scene.camera(scene.yaw,scene.pitch,Math.max(0.25,Math.min(3,scene.zoom*d.getScaleFactor())));requestRender();return true;}});}
        @Override protected void onDraw(Canvas c){c.drawColor(0xff253249);if(image!=null){int side=Math.min(getWidth(),getHeight()),left=(getWidth()-side)/2,top=(getHeight()-side)/2;c.drawBitmap(image,null,new Rect(left,top,left+side,top+side),paint);}}
        @Override public boolean onTouchEvent(MotionEvent e){if(busy||scene==null)return false;pinch.onTouchEvent(e);switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:x=e.getX();y=e.getY();getParent().requestDisallowInterceptTouchEvent(true);return true;case MotionEvent.ACTION_MOVE:if(!pinch.isInProgress()&&e.getPointerCount()==1){double yaw=scene.yaw+(e.getX()-x)*0.01;yaw=Math.atan2(Math.sin(yaw),Math.cos(yaw));scene=scene.camera(yaw,Math.max(-1.5,Math.min(1.5,scene.pitch+(e.getY()-y)*0.01)),scene.zoom);requestRender();}x=e.getX();y=e.getY();return true;case MotionEvent.ACTION_UP:performClick();case MotionEvent.ACTION_CANCEL:persist();getParent().requestDisallowInterceptTouchEvent(false);return true;default:x=e.getX();y=e.getY();return true;}}
        @Override public boolean performClick(){super.performClick();return true;}
    }
}
