package com.bia.mobile;
import java.util.*;
/** Picking uses the same orthographic camera and fixed framing as the motion renderer. */
final class ScenePicking {
    static double[] pick(SceneEngine.Scene s,SceneEngine.Scene frame,int object,double u,double v){
        double[] lo={Double.MAX_VALUE,Double.MAX_VALUE,Double.MAX_VALUE},hi={-Double.MAX_VALUE,-Double.MAX_VALUE,-Double.MAX_VALUE};ArrayList<CreativeEngine.Mesh> bounds=new ArrayList<>();for(SceneEngine.Item i:frame.items){CreativeEngine.Mesh m=SceneEngine.world(i);bounds.add(m);for(double[] p:m.vertices)for(int k=0;k<3;k++){lo[k]=Math.min(lo[k],p[k]);hi[k]=Math.max(hi[k],p[k]);}}double[] center={(lo[0]+hi[0])/2,(lo[1]+hi[1])/2,(lo[2]+hi[2])/2};double radius=0;for(CreativeEngine.Mesh m:bounds)for(double[] p:m.vertices){double d=0;for(int k=0;k<3;k++)d+=(p[k]-center[k])*(p[k]-center[k]);radius=Math.max(radius,Math.sqrt(d));}double scale=0.43*s.zoom/Math.max(0.001,radius),closest=-Double.MAX_VALUE;double[] result=null;
        for(int index=0;index<s.items.size();index++){SceneEngine.Item item=s.items.get(index);CreativeEngine.Mesh world=SceneEngine.world(item),local=SceneEngine.primitive(item);double[][] projected=new double[world.vertices.size()][3];for(int i=0;i<projected.length;i++){double[] p=world.vertices.get(i),r=SceneEngine.camera(new double[]{p[0]-center[0],p[1]-center[1],p[2]-center[2]},s);projected[i]=new double[]{0.5+r[0]*scale,0.5-r[1]*scale,r[2]};}for(int[] f:world.faces){double[] a=projected[f[0]],b=projected[f[1]],c=projected[f[2]];double area=(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);if(area>=-1e-12)continue;double w0=((b[0]-u)*(c[1]-v)-(b[1]-v)*(c[0]-u))/area,w1=((c[0]-u)*(a[1]-v)-(c[1]-v)*(a[0]-u))/area,w2=1-w0-w1;if(w0<0||w1<0||w2<0)continue;double z=w0*a[2]+w1*b[2]+w2*c[2];if(z<=closest)continue;closest=z;result=null;if(index==object){result=new double[3];for(int k=0;k<3;k++)result[k]=w0*local.vertices.get(f[0])[k]+w1*local.vertices.get(f[1])[k]+w2*local.vertices.get(f[2])[k];}}}return result;
    }
}
